Q1. Create a Pandas Series that contains the following data: 4, 8, 15, 16, 23, and 42. Then, print the series.

In [20]:
import pandas as pd
ds=pd.Series([4, 8, 15, 16, 23, 42])

Q2. Create a variable of list type containing 10 elements in it, and apply pandas.Series function on the variable print it.

In [27]:
import pandas as pd
movies_list=['Matrix', '3 idiots', 'Iron Man', 'Avenger']
pd.Series(movies_list, name='Movie List')

0      Matrix
1    3 idiots
2    Iron Man
3     Avenger
Name: Movie List, dtype: object

Q3. Create a Pandas DataFrame that contains the following data:
![image.png]()

Then, print the DataFrame.

In [5]:
pd.DataFrame({
    'Name':['Alice','Bob','Claire'],
    'Age':[25,30,27],
    'Gender':['Female','Male','Female']
})

     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   27  Female

Q4. What is ‘DataFrame’ in pandas and how is it different from pandas.series? Explain with an example.

A DataFrame in Pandas is a 2-dimensional, mutable, tabular data structure, similar to a spreadsheet or SQL table. It consists of rows and columns, where:

**Columns** represent features/attributes (like fields in a database).
**Rows** represent individual records (like entries in a table).

It can hold multiple data types, such as integers, floats, strings, etc.

**Difference between DataFrame and Series**:
**Dimensionality**:
Series: One-dimensional (like a list or an array).
DataFrame: Two-dimensional (like a table with rows and columns).

**Structure**:
Series has only one column and a corresponding index.
DataFrame contains multiple columns, and each column is essentially a Series.

**Data Types**:
A Series can store homogeneous data (though technically it can hold any type), while a DataFrame can store different types in different columns.

Q5. What are some common functions you can use to manipulate data in a Pandas DataFrame? Can you give an example of when you might use one of these functions?

There are multiple common functions are avialble in Pandas like head(), tail(), dtype, info(), describe() etc.
Find the below commonly used function list in pandas.


1.   **Data Exploration**: Use **head**(), **tails**(), **info**(), and **describe**() to explore datasets.
2.   **Data Cleaning**: Use **dropna**(), **fillna**(), and **apply**() to handle missing or incorrect data.
3. **Data Transformation**: Use **groupby**(), **sort_values**(), and **drop**() for aggregations, sorting, and restructuring data.

In [22]:
import pandas as pd

# Creating a Pandas Series
series = pd.Series([10, 20, 30, 40], name="Scores")

# Creating a Pandas DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 88, 95]
}
df = pd.DataFrame(data)

# Printing the Series and DataFrame
print("Series:")
print(series)

print("\nDataFrame:")
print(df)

Series:
0    10
1    20
2    30
3    40
Name: Scores, dtype: int64

DataFrame:
      Name  Age  Score
0    Alice   24     85
1      Bob   27     90
2  Charlie   22     88
3    David   32     95

Q6. Which of the following is mutable in nature Series, DataFrame, Panel?

Answer: Series and DataFrame are mutable, while Panel is also mutable but less commonly used and considered deprecated in recent versions of Pandas.

Q7. Create a DataFrame using multiple Series. Explain with an example.

In [28]:
pd.DataFrame({
    'Course': ['Data Science', 'Web Development', 'Java'],
    'Duration': ['9 Month', '3 Month', '6 Month'],
    'Price': [100000, 5000, 10000],
    'Mentor': ['Sudhanshu  Kumar', 'Krish Naik', 'Abhishek Kumar']
})

            Course Duration   Price            Mentor
0     Data Science  9 Month  100000  Sudhanshu  Kumar
1  Web Development  3 Month    5000        Krish Naik
2             Java  6 Month   10000    Abhishek Kumar